### ISSUE TITLE
gtp5g wont build on ubuntu 20.04.5 kernel 5.4.0-050400-generic with 'pktinfo.c:84:8: error: too many arguments to function ‘rt->dst.ops->update_pmtu’'

### ISSUE THREAD

**Issue by anichari** [free5gc/gtp5g#66]
Hello:

I'm trying to build and install gtp5g on my 20.04.5 Ubuntu VM with kernel 5.4.0-050400-generic but am hitting the following error. Please help me understand if this is known and if there are any workarounds or fixes.

```
root@rigel:~# hostnamectl
   Static hostname: rigel
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a8ad6bb1840c4ced8a58115da013d9de
           Boot ID: bf5d204c7f244510ba845dd97f9108f9
    Virtualization: kvm
  Operating System: Ubuntu 20.04.5 LTS
            Kernel: Linux 5.4.0-050400-generic
      Architecture: x86-64
root@rigel:~# cd gtp5g/
root@rigel:~/gtp5g# make clean && make
make -C /lib/modules/5.4.0-050400-generic/build M=/root/gtp5g clean
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-050400-generic'
  CLEAN   /root/gtp5g/Module.symvers
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-050400-generic'
make -C /lib/modules/5.4.0-050400-generic/build M=/root/gtp5g modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-050400-generic'
  CC [M]  /root/gtp5g/src/gtp5g.o
  CC [M]  /root/gtp5g/src/log.o
  CC [M]  /root/gtp5g/src/util.o
  CC [M]  /root/gtp5g/src/gtpu/dev.o
  CC [M]  /root/gtp5g/src/gtpu/encap.o
  CC [M]  /root/gtp5g/src/gtpu/hash.o
  CC [M]  /root/gtp5g/src/gtpu/link.o
  CC [M]  /root/gtp5g/src/gtpu/net.o
  CC [M]  /root/gtp5g/src/gtpu/pktinfo.o
/root/gtp5g/src/gtpu/pktinfo.c: In function ‘ip4_find_route’:
/root/gtp5g/src/gtpu/pktinfo.c:84:8: error: too many arguments to function ‘rt->dst.ops->update_pmtu’
   84 |        rt->dst.ops->update_pmtu(&rt->dst, NULL, skb, mtu, false);
      |        ^~
make[2]: *** [scripts/Makefile.build:266: /root/gtp5g/src/gtpu/pktinfo.o] Error 1
make[1]: *** [Makefile:1652: /root/gtp5g] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-050400-generic'
make: *** [Makefile:79: module] Error 2
root@rigel:~/gtp5g#
```

**Comment by anichari** [comment]
I'm able to compile and load the module with 5.4.0-1084-kvm kernel version on the same machine. Looking for workarounds/suggestions to get it to work on 5.4.0 generic.
```
root@rigel:~# uname -a
Linux rigel 5.4.0-1084-kvm #90-Ubuntu SMP Tue Jan 10 22:07:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@rigel:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
root@rigel:~# uname -r
5.4.0-1084-kvm
root@rigel:~# hostnamectl
   Static hostname: rigel
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a8ad6bb1840c4ced8a58115da013d9de
           Boot ID: 41a6a86552d94c378c4621533711532e
    Virtualization: kvm
  Operating System: Ubuntu 20.04.5 LTS
            Kernel: Linux 5.4.0-1084-kvm
      Architecture: x86-64
root@rigel:~# cd gtp5g/
root@rigel:~/gtp5g# make clean && make
make -C /lib/modules/5.4.0-1084-kvm/build M=/root/gtp5g clean
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-1084-kvm'
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-1084-kvm'
make -C /lib/modules/5.4.0-1084-kvm/build M=/root/gtp5g modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-1084-kvm'
  CC [M]  /root/gtp5g/src/gtp5g.o
  CC [M]  /root/gtp5g/src/log.o
  CC [M]  /root/gtp5g/src/util.o
  CC [M]  /root/gtp5g/src/gtpu/dev.o
  CC [M]  /root/gtp5g/src/gtpu/encap.o
  CC [M]  /root/gtp5g/src/gtpu/hash.o
  CC [M]  /root/gtp5g/src/gtpu/link.o
  CC [M]  /root/gtp5g/src/gtpu/net.o
  CC [M]  /root/gtp5g/src/gtpu/pktinfo.o
  CC [M]  /root/gtp5g/src/genl/genl.o
  CC [M]  /root/gtp5g/src/genl/genl_version.o
  CC [M]  /root/gtp5g/src/genl/genl_pdr.o
  CC [M]  /root/gtp5g/src/genl/genl_far.o
  CC [M]  /root/gtp5g/src/genl/genl_qer.o
  CC [M]  /root/gtp5g/src/genl/genl_urr.o
  CC [M]  /root/gtp5g/src/genl/genl_report.o
  CC [M]  /root/gtp5g/src/genl/genl_bar.o
  CC [M]  /root/gtp5g/src/pfcp/api_version.o
  CC [M]  /root/gtp5g/src/pfcp/pdr.o
  CC [M]  /root/gtp5g/src/pfcp/far.o
  CC [M]  /root/gtp5g/src/pfcp/qer.o
  CC [M]  /root/gtp5g/src/pfcp/urr.o
  CC [M]  /root/gtp5g/src/pfcp/bar.o
  CC [M]  /root/gtp5g/src/pfcp/seid.o
  CC [M]  /root/gtp5g/src/proc.o
  LD [M]  /root/gtp5g/gtp5g.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /root/gtp5g/gtp5g.mod.o
  LD [M]  /root/gtp5g/gtp5g.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-1084-kvm'
root@rigel:~/gtp5g# make install
cp gtp5g.ko /lib/modules/5.4.0-1084-kvm/kernel/drivers/net
modprobe udp_tunnel
/sbin/depmod -a
modprobe gtp5g
echo "gtp5g" >> /etc/modules
root@rigel:~/gtp5g#
```

**Comment by anichari** [comment]
An UPDATE:

I was able to get the make to work after removed the conditional check in the pktinfo.c file , but though this is a work-around, this obviously requires some attention in the code.

```
root@rigel:~/gtp5g# git diff
diff --git a/src/gtpu/pktinfo.c b/src/gtpu/pktinfo.c
index 255ae52..5fa0e75 100644
--- a/src/gtpu/pktinfo.c
+++ b/src/gtpu/pktinfo.c
@@ -80,11 +80,12 @@ struct rtable *ip4_find_route(struct sk_buff *skb, struct iphdr *iph,
         mtu = dst_mtu(&rt->dst);
     }

-#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 4, 0) || defined(RHEL8)
+/*#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 4, 0) || defined(RHEL8)
        rt->dst.ops->update_pmtu(&rt->dst, NULL, skb, mtu, false);
 #else
        rt->dst.ops->update_pmtu(&rt->dst, NULL, skb, mtu);
-#endif
+#endif*/
+    rt->dst.ops->update_pmtu(&rt->dst, NULL, skb, mtu);

     if (!skb_is_gso(skb) && (iph->frag_off & htons(IP_DF)) &&
         mtu < ntohs(iph->tot_len)) {
root@rigel:~/gtp5g#
```

**Comment by afcidk** [comment]
An additional parameter `confirm_neigh` is added to `update_pmtu` after Linux 5.4.8.
I'll create a PR to fix this.

Reference: https://lwn.net/Articles/808734/
