### ISSUE TITLE
Does not compile with linux v6.9 or greater

### ISSUE THREAD

**Issue by manuel2258** [free5gc/gtp5g#109]
### Describe the bug
The kernel module 'gtp5g' (v0.9.0 10b1314) does not compile with kernel headers greater than v6.9.

### How to reproduce
Acquire linux system with kernel newer than v6.9
```
$ git clone https://github.com/free5gc/gtp5g.git && cd gtp5g
$ make
make -C /lib/modules/6.9.6-200.fc40.x86_64/build M=/home/manuel/projects/gtp5g modules
make[1]: Entering directory '/usr/src/kernels/6.9.6-200.fc40.x86_64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 14.1.1 20240607 (Red Hat 14.1.1-5)
  You are using:           gcc (GCC) 14.1.1 20240620 (Red Hat 14.1.1-6)
  CC [M]  /home/manuel/projects/gtp5g/src/gtpu/pktinfo.o
/home/manuel/projects/gtp5g/src/gtpu/pktinfo.c:16:5: warning: no previous prototype for ‘network_and_transport_header_len’ [-Wmissing-prototypes]
   16 | u64 network_and_transport_header_len(struct sk_buff *skb) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/manuel/projects/gtp5g/src/gtpu/pktinfo.c:129:16: warning: no previous prototype for ‘ip4_find_route_simple’ [-Wmissing-prototypes]
  129 | struct rtable *ip4_find_route_simple(struct sk_buff *skb,
      |                ^~~~~~~~~~~~~~~~~~~~~
/home/manuel/projects/gtp5g/src/gtpu/pktinfo.c: In function ‘ip4_find_route_simple’:
/home/manuel/projects/gtp5g/src/gtpu/pktinfo.c:139:23: error: implicit declaration of function ‘RT_CONN_FLAGS’ [-Wimplicit-function-declaration]
  139 |     fl4->flowi4_tos = RT_CONN_FLAGS(sk);
      |                       ^~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:244: /home/manuel/projects/gtp5g/src/gtpu/pktinfo.o] Error 1
make[2]: *** [/usr/src/kernels/6.9.6-200.fc40.x86_64/Makefile:1930: /home/manuel/projects/gtp5g] Error 2
make[1]: *** [Makefile:252: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.9.6-200.fc40.x86_64'
make: *** [Makefile:84: module] Error 2
```

### Expected behavior
Compilation finishes and module can be installed.

### Additional context
Seems like the used macro RT_CONN_FLAGS was removed:  
- https://github.com/torvalds/linux/blob/v6.8/include/net/route.h#L40  
- https://github.com/torvalds/linux/blob/v6.9/include/net/route.h  

### Fix

The issue can be fixed by manually patching the macro usage with the expanded version:
```
diff --git a/src/gtpu/pktinfo.c b/src/gtpu/pktinfo.c
index 48503d1..2fe3e5a 100644
--- a/src/gtpu/pktinfo.c
+++ b/src/gtpu/pktinfo.c
@@ -74,7 +74,7 @@ struct rtable *ip4_find_route(struct sk_buff *skb, struct iphdr *iph,
     fl4->flowi4_oif = sk->sk_bound_dev_if;
     fl4->daddr = daddr;
     fl4->saddr = (saddr ? saddr : inet_sk(sk)->inet_saddr);
-    fl4->flowi4_tos = RT_CONN_FLAGS(sk);
+    fl4->flowi4_tos = RT_TOS(inet_sk(sk)->tos) | sock_flag(sk, SOCK_LOCALROUTE);
     fl4->flowi4_proto = sk->sk_protocol;

     rt = ip_route_output_key(dev_net(gtp_dev), fl4);
@@ -136,7 +136,7 @@ struct rtable *ip4_find_route_simple(struct sk_buff *skb,
     fl4->flowi4_oif = sk->sk_bound_dev_if;
     fl4->daddr = daddr;
     fl4->saddr = (saddr ? saddr : inet_sk(sk)->inet_saddr);
-    fl4->flowi4_tos = RT_CONN_FLAGS(sk);
+    fl4->flowi4_tos = RT_TOS(inet_sk(sk)->tos) | sock_flag(sk, SOCK_LOCALROUTE);
     fl4->flowi4_proto = sk->sk_protocol;

     rt = ip_route_output_key(dev_net(gtp_dev), fl4);
```
Is that a desired solution? I'm running the manually patched version for a month now, and it seems to work fine.

**Comment by hnorkowski** [comment]
I can confirm this! I had the same issue and solved it the same way as you did and it seems to work fine!
